### PR TITLE
upgrade to latest abstractplotting

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by Datseris** [comment]
I'll have to test this to see how many things break. Any name changes so far? (LAxis -> Axis?)

**Comment by SimonDanisch** [comment]
Nope, I tested most examples and they worked fine, as far as I can tell ;)

**Comment by Datseris** [comment]
Hi @SimonDanisch I am now working to get this PR up to speed and merge it! I am encountering the scary

```
WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:924 overwritten in module Optim at C:\Users\datse\.julia\packages\Optim\Agd3B\src\multivariate\precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:924 overwritten in module Optim at C:\Users\datse\.julia\packages\Optim\Agd3B\src\multivariate\precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:924 overwritten in module Optim at C:\Users\datse\.julia\packages\Optim\Agd3B\src\multivariate\precon.jl:23.
  ** incremental compilation may be fatally broken for this module **
```
when abstract plotting gets pre compiled. Should I worry?

**Comment by Datseris** [comment]
@SimonDanisch I am failing to run `examples/orbitdiagram.jl` because of:
```

WARNING: could not import AbstractPlotting.combine into StatsMakie
ERROR: LoadError: LoadError: UndefVarError: PlotList not defined
Stacktrace:
 [1] top-level scope at C:\Users\datse\.julia\packages\StatsMakie\MwUVz\src\group\dodge.jl:30
 [2] include(::Function, ::Module, ::String) at .\Base.jl:380
 [3] include at .\Base.jl:368 [inlined]
 [4] include(::String) at C:\Users\datse\.julia\packages\StatsMakie\MwUVz\src\StatsMakie.jl:1
 [5] top-level scope at C:\Users\datse\.julia\packages\StatsMakie\MwUVz\src\StatsMakie.jl:39
 [6] include(::Function, ::Module, ::String) at .\Base.jl:380
 [7] include(::Module, ::String) at .\Base.jl:368
 [8] top-level scope at none:2
 [9] eval at .\boot.jl:331 [inlined]
 [10] eval(::Expr) at .\client.jl:467
 [11] top-level scope at .\none:3
in expression starting at C:\Users\datse\.julia\packages\StatsMakie\MwUVz\src\group\dodge.jl:30
in expression starting at C:\Users\datse\.julia\packages\StatsMakie\MwUVz\src\StatsMakie.jl:39
```

can you give me some feedback how to go about it?

**Comment by Datseris** [comment]
I also have the problem that in the cited example (which now works because I've silenced stats makie) the alpha property of my plot doesn't work any more. it has no impact.

Was there any change regarding markers, their default values, and how alpha works?

**Comment by Datseris** [comment]
this is how I used to do alpha:

```
color = lift(a -> RGBAf0(0,0,0,a), α)
    scatter!(odax, od_obs, markersize = 0.002, color = color)

```

**Comment by Datseris** [comment]
Yeap, alpha doesn't seem to work this way anymore?

**Comment by Datseris** [comment]
Alright, I've fixed alpha. Turns out there was a breaking change that now by default markers have non-zero stroke width. I now do:
```
    color = lift(a -> RGBAf0(0,0,0,a), α)
    scatter!(odax, od_obs, markersize = 0.01, color = color, strokewidth = 0.0)
```
The problem that remains is that `markersize` has no impact anymore. I can do it as large or as small as I want, doesn't change anything.

**Comment by Datseris** [comment]
@SimonDanisch I need to report something perhaps more critical. The billiards application now stutters. If you may, please have a look at running:
```julia
using DynamicalBilliards, InteractiveChaos, Makie

bd = billiard_mushroom(1.0f0, 0.2f0, 1.0f0, 0.0f0; door = false)
interactive_billiard(bd, tail = 1000)
```

(that is the application I've shown in your JuliaCon talk)

The application now stutters, even though I haven't touched something from my end:

sinaiapp

**Comment by Datseris** [comment]
Alright after re-installing everything, I don't get the stuttering anymore.

**Comment by SimonDanisch** [comment]
Can you report your version?

**Comment by Datseris** [comment]
> Can you report your version?

I've solved all problems now, besides the fact that StatsMakie doesn't work (but also I've learned in Slack that it is being "phased out").

**Comment by Datseris** [comment]
@SebastianM-C I'll merge this for the sole purpose of having the master branch being runnable, because I am developing a new application. If you get the chance to update the Histogram code feel free to open a new PR!

**Pull request merged**
