### PR TITLE
Update to AbstractPlotting 0.15

### PR DESCRIPTION
**Pull request by Datseris**
currently WIP

### CODE REVIEW

**Comment by Datseris** [comment]
@Libbum can you please have a look at the file `examples/agents_daisyworld.jl`? I think the latest changes we've made to data aggregation have broken something. Specifically, I get:

```
LoadError: No possible aggregation for breed using black
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] multi_agent_agg_types!(::Array{Array{T,1} where T,1}, ::Tuple{DataType,DataType}, ::Array{String,1}, ::AgentBasedModel{Union{Agents.Models.Daisy, Agents.Models.Land},GridSpace{2,true},Agents.Models.var"#daisysched#19",Dict{Symbol,Any}}, ::Array{Tuple{Function,Function},1}) at C:\Users\datse\.julia\dev\Agents\ ::AgentBasedMosrc\simulations\collect.jl:340                                                                           ct{Symbol,Any}}
 [3] init_agent_dataframe(::AgentBasedModel{Union{Agents.Models.Daisy, Agents.Models.Land},GridSpace{2,true},Agents.Models.var"#daisysched#19",Dict{Symbol,Any}}, ::Array{Tuple{Function,Function},1}) at C:\Usersue},Agents.Mode\datse\.julia\dev\Agents\src\simulations\collect.jl:288
```

while my data collection definitions are:
```julia
black(y) = count(x -> x == :black, y)
white(y) = count(x -> x == :white, y)
breed(a) = a isa Daisy ? a.breed : :land
gettemperature(a) = a isa Land ? a.temperature : missing
meantemperature(x) = mean(skipmissing(x))
adata = [(breed, black), (breed, white), (gettemperature, meantemperature)]
mdata = [:solar_luminosity]
```

**Comment by Libbum** [comment]
Sure, I'll take a look soon.

**Comment by Libbum** [comment]
I don't have push access to this branch, but just change those above lines to this:
```julia
black(a) = a.breed == :black
white(a) = a.breed == :white
daisies(a) = a isa Daisy
land(a) = a isa Land
adata = [(black, count, daisies), (white, count, daisies), (:temperature, mean, land)]
mdata = [:solar_luminosity]
```

which lines up with the current examples in Agents#master

**Comment by Datseris** [comment]
Thanks so much man!!!

**Pull request merged**
