### PR TITLE
[WIP] Update trajectory_highlighter

### PR DESCRIPTION
**Pull request by SebastianM-C**
This updates `trajectory_highlighter` for the most recent changes in Makie.

- Fix `UndefVarError` for `color`
- get_series_idx now returns the adjusted index

This is not yet ready because changing the alpha for the histograms does not work due to https://github.com/JuliaPlots/Makie.jl/issues/617

### CODE REVIEW

**Comment by Datseris** [comment]
Okay, let's wait a bit until the Makie-end has some progress. I will also add some updates into this PR, because in #7 I change the design of InteractiveChaos a bit to use `Requires` (since now it provides applications for pretty much all of JuliaDynamics, hooray!), so some headers need to be added here and there.

**Comment by SebastianM-C** [comment]
The next step is to wait for a solution to https://github.com/JuliaPlots/Makie.jl/issues/619

**Comment by Datseris** [comment]
@SebastianM-C the linked issue was closed, do we wait for something else, or time for me to also review/help/commit/merge ?

**Comment by SebastianM-C** [comment]
Sorry for the delay. I'll implement a workaround a move on with this. I think that waiting for an API in Makie would take too long.

**Comment by Datseris** [comment]
@SebastianM-C I've just run the code locally and it worked fine for me!

I've noticed that MakieLayout is about to be merged into Makie though. Do we have to update this code to use the Makie layout stuff instead of the old makie stuff?

**Comment by Datseris** [comment]
In fact, is it possible to do bar plots in MakieLayout? Because if yes, only the 3D stuff use old code.

**Comment by SebastianM-C** [comment]
The most fragile part is computing the index correctly. I tried to hardcode as little as possible, but it could break again in the future.
The best solution would be to use an API supported by Makie (https://github.com/JuliaPlots/Makie.jl/issues/240#issuecomment-645615812). One of the current problems is that if you manage to click on an axis line (from the grid), you could potentially get some strange errors and undefined behavior.

> is it possible to do bar plots in MakieLayout

You mean to layout the composed scene with MakieLayout instead of `vbox`?
I don't think it would be a good idea to hardcode MakieLayout-specific code now, as from what I understand, things like `LAxis` could disappear after the merge (I'm not 100% sure, better ask someone who knows better).
We could wait for the merge and then update the code with the new API (and maybe we won't have to make a distinction between the 2D and 3D cases).

**Pull request merged**
